Models/AppIdentityRole.cs
using Microsoft.AspNetCore.Identity;
namespace SimpleBankSystem.Models
{
    public class AppIdentityRole : IdentityRole
    {
        
    }
}

Models/AppIdentityUser.cs
using Microsoft.AspNetCore.Identity;
namespace SimpleBankSystem.Models
{
    public class AppIdentityUser : IdentityUser
    {
        
    }
}

Models/ApplicationDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.AspNetCore.Identity;
namespace SimpleBankSystem.Models
{
    public class ApplicationDbContext : IdentityDbContext<AppIdentityUser, AppIdentityRole, string>
    {
     public DbSet<BankAccount> BankAccounts { get; set; }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            :base(options)
        {

        }
         protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
           
            modelBuilder.Entity<AppIdentityUser>(entity => { 
                entity.Property(m => m.Email).HasMaxLength(127); 
                entity.Property(m => m.NormalizedEmail).HasMaxLength(127); 
                entity.Property(m => m.NormalizedUserName).HasMaxLength(127); 
                entity.Property(m => m.UserName).HasMaxLength(127); 
            }); 
            modelBuilder.Entity<AppIdentityRole>(entity => { 
                entity.Property(m => m.Name).HasMaxLength(127); 
                entity.Property(m => m.NormalizedName).HasMaxLength(127); 
            }); 
            modelBuilder.Entity<IdentityUserLogin<string>>(entity => 
            { 
                entity.Property(m => m.LoginProvider).HasMaxLength(127); 
                entity.Property(m => m.ProviderKey).HasMaxLength(127); 
            }); 
            modelBuilder.Entity<IdentityUserRole<string>>(entity => 
            { 
                entity.Property(m => m.UserId).HasMaxLength(127); 
                entity.Property(m => m.RoleId).HasMaxLength(127); 
            }); 
            modelBuilder.Entity<IdentityUserToken<string>>(entity => 
            { 
                entity.Property(m => m.UserId).HasMaxLength(127); 
                entity.Property(m => m.LoginProvider).HasMaxLength(127); 
                entity.Property(m => m.Name).HasMaxLength(127); 
            });
        }

    }
}

Models/BankAccount.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SimpleBankSystem.Models
{
    public class BankAccount
    {
        public int Id { get; set; }

        
        public long AccountNumber { get; set; }


        [Required(ErrorMessage = "Please specify an account name.")]
        [MaxLength(25, ErrorMessage = "The account name must not exced 25 characters.")]
        public string AccountName { get; set; }

        [Required(ErrorMessage = "Please specify an account password.")]
        [MinLength(8, ErrorMessage = "The password must contain at least 8 characters.")]
        [MaxLength(10, ErrorMessage = "The password must not exced 10 characters.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please specify an account balance.")]
        public decimal Balance { get; set; }

        public DateTime CreatedDate { get; set; }

        public string AccountOwnerId { get; set; }

         [ForeignKey("AccountOwnerId")]
         public AppIdentityUser AccountOwner { get; set; }

    }
}

Models/Repository/FakeRepository/FakeBankAccountRepository.cs
using System;
using SimpleBankSystem.Models;
using SimpleBankSystem.Models.Repository;
using System.Collections.Generic;
using System.Linq;
namespace SimpleBankSystem.Models.Repository.FakeRepository
{
    public class FakeBankAccountRepository : IBankAccountRepository
    {
       public List<BankAccount> BankAccounts => new List<BankAccount>
       {
           // Password = Mido@1995
           new BankAccount() { Id = 1, AccountName = "XYZ", AccountNumber = 340731158653492, CreatedDate = DateTime.Now, Balance = 5000.87m, AccountOwnerId = "c2122d17-2118-46d2-a41a-5b20c152d8c1", Password = "cb2939c1bf16ec31716d59c4e5abc379" },
           // Password = Mido@
           new BankAccount() { Id = 2, AccountName = "ABC", AccountNumber = 349602687801483, CreatedDate = DateTime.Now, Balance = 8000.50m, AccountOwnerId = "a1b642f9-4e0a-43a8-a80a-67591aadcf24", Password = "11e2559bfc8396d93f87862c26217a9c"},
           // Password = Hello
           new BankAccount() { Id = 3, AccountName = "MNO", AccountNumber = 349602687801483, CreatedDate = DateTime.Now, Balance = 7894.56m, AccountOwnerId = "c2122d17-2118-46d2-a41a-5b20c152d8c1", Password = "8b1a9953c4611296a827abf8c47804d7"  },           
       };
       public List<BankAccount> GetBankAccountForUser(string userId)
       {
           return this.BankAccounts.Where(bk => bk.AccountOwnerId.Equals(userId)).ToList();
       }
    }
}

Models/Repository/FakeRepository/FakeUserRepository.cs
using System;
using SimpleBankSystem.Models;
using SimpleBankSystem.Models.Repository;
using System.Collections.Generic;
using System.Linq;
namespace SimpleBankSystem.Models.Repository.FakeRepository
{
    public class FakeUserRepository : IUserRepository
    {
        public List<AppIdentityUser> Users => new List<AppIdentityUser>()
        {
            new AppIdentityUser(){ Id = "c2122d17-2118-46d2-a41a-5b20c152d8c1", Email = "user@email.com" },
            new AppIdentityUser(){ Id = "a1b642f9-4e0a-43a8-a80a-67591aadcf24", Email = "anotherUser@email.com" }
        };

        public AppIdentityUser GetOneUserById(string userId)
        {
            return this.Users.SingleOrDefault(u => u.Id.Equals(userId));
        }

        public AppIdentityUser GetOneUserByEmail(string userEmail)
        {
            return this.Users.SingleOrDefault(u => u.Email.Equals(userEmail));
        }
    }
}

Models/Repository/IBankAccountRepository.cs
using SimpleBankSystem.Models;
using System.Collections.Generic;
namespace SimpleBankSystem.Models.Repository
{
    public interface IBankAccountRepository
    {
        List<BankAccount> BankAccounts { get; }

        List<BankAccount> GetBankAccountForUser(string userId);
    }
}

Models/Repository/IUserRepository.cs
using SimpleBankSystem.Models;
using System.Collections.Generic;
namespace SimpleBankSystem.Models.Repository
{
    public interface IUserRepository
    {
        List<AppIdentityUser> Users { get; }

        AppIdentityUser GetOneUserById(string userId);

        AppIdentityUser GetOneUserByEmail(string userId);
    }
}

Controllers/BankAccountController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using SimpleBankSystem.Models.Repository;
using SimpleBankSystem.Models;
namespace Simple_Bank_System.Controllers
{
    public class BankAccountController : Controller
    {
        private IBankAccountRepository bankAccountRepository;

        private IUserRepository userRepository;
        public BankAccountController(IBankAccountRepository bankRepo, IUserRepository userRepo)
        {
            bankAccountRepository = bankRepo;
            userRepository = userRepo;
        }
        public ActionResult Index() => 
        View(bankAccountRepository.GetBankAccountForUser(userRepository.GetOneUserByEmail("user@email.com").Id));
    }
}

Views/BankAccount/Index.cshtml
@model List<BankAccount>
@{
    ViewBag.Title = "Index";
}
<div class="row container-fluid">
    <div class="col-md-12">
        <h4>List of accounts:</h4>
        <br/>
        <a asp-action="new" asp-controller="BankAccount" class="btn btn-outline-primary">+New account</a>
        @if(Model.Count > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <td>Account Number:</td>
                    <td>Account Name:</td>
                    <td>Balance:</td>
                    <td>Creation date:</td>            
                </thead>
                <tbody>
                    <!-- Display data using foreach loop -->
                    @foreach(var bankAccount in Model)
                    {
                        <tr>
                            <td>@bankAccount.AccountNumber</td>
                            <td>@bankAccount.AccountName</td>
                            <td>@bankAccount.Balance</td>
                            <td>@bankAccount.CreatedDate</td>  
                        </tr>
                    } 
                </tbody>
            </table>
        }
        else
        {
            <p>No accounts to display, you can create one from the link above.</p>
        }
    </div>
</div>

Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="width=device-width" />
            <title>@ViewBag.Title - Simple Bank System</title>
            
            <environment names="Development">
                <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
            </environment>
            <environment names="Staging,Production">
                <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />     
            </environment>

        </head>
        <body class="container-fluid">
            @Html.Partial("_NavigationBar")
            <div class="row jumbotron text-center">
                <p class="text-center">
                    <h3>Simple Bank System.</h3>
                </p>
            </div>
            @RenderBody()   
        <environment names="Development">
            <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="/lib/jQuery/dist/jquery.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
            <script src="/lib/jQuery/dist/jquery.min.js" ></script>
        </environment>
        </body>
    </html>

Views/Shared/_NavigationBar.cshtml
<nav class="navbar row navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">SBS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav ml-auto">
        <li class="nav-item active">
            <a class="nav-link" href="#">Deposit </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Withdraw</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Transfer funds</a>
        </li>
            <li class="nav-item active">
            <a class="nav-link" href="#">Show transaction report    </a>
        </li>
        </ul>
    </div>
</nav>